name: Sync quiz with Canvas

on:
  push:
    branches: [master, main]
    paths:
      - "README.md"
      - "questions/*.md"

jobs:
  sync:
    name: Sync with Canvas

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install gems
        run: |
          git clone git@github.com:learn-co-curriculum/github-to-canvas-quiz.git
          cd github-to-canvas-quiz
          bundle exec rake install
          cd ..

      # Secret stored in learn-co-curriculum Settings/Secrets
      - name: Sync from markdown
        run: github-to-canvas-quiz align
        env:
          CANVAS_API_KEY: ${{ secrets.CANVAS_API_KEY }}
          CANVAS_API_PATH: ${{ secrets.CANVAS_API_PATH }}